#! /bin/bash

TMP=/tmp
DAEMON=iscsid
TOOL=iscsictl
KEXT=iSCSIInitiator.kext
MAN1=iscsictl.8
MAN2=iscsid.8

# Get minor version of the OS
OSX_MINOR_VER=$(sw_vers -productVersion | awk -F '.' '{print $2}')

# Minor version of OS X Mavericks
OSX_MAVERICKS_MINOR_VER="9"

if [ "$OSX_MINOR_VER" -ge "$OSX_MAVERICKS_MINOR_VER" ]; then
    KEXT_DST=/Library/Extensions
else
    KEXT_DST=/System/Library/Extensions
fi

# Copy kernel extensions & load it
sudo cp -R $TMP/$KEXT $KEXT_DST/$KEXT
sudo chmod -R 755 $KEXT_DST/$KEXT
sudo chown -R root:wheel $KEXT_DST/$KEXT

# Copy daemon & set permissions
sudo mkdir -p /Library/PrivilegedHelperTools/
sudo cp $TMP/$DAEMON /Library/PrivilegedHelperTools/$DAEMON
sudo cp $TMP/com.github.iscsi-osx.iscsid.plist /Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist
sudo chmod -R 744 /usr/local/$DAEMON
sudo chmod 644 /Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist
sudo chown root:wheel /Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist

# Copy user tool
sudo cp $TMP/$TOOL /usr/local/bin/$TOOL
sudo chmod +x /usr/local/bin/$TOOL

# Copy man pages
sudo cp $TMP/$MAN1 /usr/share/man/man8
sudo cp $TMP/$MAN2 /usr/share/man/man8

# Load kernel extension
sudo kextload /Library/Extensions/$KEXT

# Start daemon
sudo launchctl load /Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist
sudo launchctl start com.github.iscsi-osx.iscsid