#! /bin/bash

TMP=/tmp
DAEMON=iscsid
TOOL=iscsictl
KEXT=iSCSIInitiator.kext
MAN1=iscsictl.8
MAN2=iscsid.8

# Copy kernel extensions & load it
sudo cp -R $TMP/$KEXT /Library/Extensions/$KEXT
sudo chmod -R 755 /Library/Extensions/$KEXT
sudo chown -R root:wheel /Library/Extensions/$KEXT

# Copy daemon & set permissions
sudo cp $TMP/$DAEMON /Library/PrivilegedHelperTools/$DAEMON
sudo cp $TMP/com.github.iscsi-osx.iscsid.plist /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist
sudo chmod -R 744 /usr/local/$DAEMON
sudo chmod 644 /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist
sudo chown root:wheel /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist

# Copy user tool
sudo cp $TMP/$TOOL /usr/local/bin/$TOOL
sudo chmod +x /usr/local/bin/$TOOL

# Copy man pages
sudo cp $TMP/$MAN1 /usr/share/man/man8
sudo cp $TMP/$MAN2 /usr/share/man/man8

# Load kernel extension
sudo kextload /Library/Extensions/$KEXT

# Start daemon
sudo launchctl load /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist
sudo launchctl start com.github.iscsi-osx.iscsid