.\" (c) 2013-2015 Nareg Sinenian. All rights reserved.
.\" This file is the UNIX man page for the iscsictl command-line utility."
.Dd November 1, 2015
.Dt ISCSICTL 8
.Os "Mac OS X"
.Sh NAME
.Nm iscsictl
.Nd iSCSI initiator configuration and management tool.
.Sh SYNOPSIS
.Nm
add target
.Ar target,portal
.Op Fl interface Ar interface
.Nm
remove target
.Ar target
.Op , Ar portal

.Nm
login
.Ar " target" Op , Ar portal
.Nm
logout
.Ar target Op , Ar portal
.Nm
mount
.Ar  "  target"
.Nm
unmount
.Ar	target

.Nm
modify initiator-config
.Op ...
.Nm
modify target-config
.Ar target Op , Ar portal
.Op ...
.Nm
modify discovery-config
.Op ...

.Nm
list initiator-config
.Nm
list target-config
.Ar target
.Nm
list discovery-config

.Nm
add discovery-portal
.Ar portal
.Op Fl interface Ar interface
.Nm
remove discovery-portal
.Ar portal

.Nm
list targets
.Nm
list luns

.Sh DESCRIPTION
The
.B iscsictl
utility is used to configure the iSCSI initiator and manage sessions.  Users may login or logout of targets after they have been defined with appropriate portals and optional authentication method, session parameters and connection parameters.  Unprivileged users cannot perform add, remove and modify operations.
.Pp
The options are as follows:
.Bl -tag -width "-discovery"
.It add
Adds an entity to the specified database.
.It modify
Modifies an existing entity in the specified database.
.It remove
Removes an existing entity from the specified database.
.It list
Lists entities in the specified database.
.It login
Logs into a target or connection.
.It logout
Logs out of a target or connection.
.El
.Pp
The
.Ar target
must be an iSCSI Qualified Name (IQN) as defined in RFC3720.  The
.Ar portal
must be a valid IP address (version 4 or 6) or a valid DNS name.  If a port other than 3620 is used, the
.Ar portal
can include a port number (e.g., <address:port>). The
.Ar interface
when specified must be a valid network interface (i.e., as listed by ifconfig). Otherwise the first available interface that supports the specified protocol is automatically used.
.Pp
If multiple connections are to be used with a single target, it is important to indicate the interfaces to be used in order to prevent conflicts.
.Pp
If the
.Ar portal
is omitted where optional, the command acts on all portals.  For example, when logging into or out of a target, a specific portal can be used otherwise the initiator will login to or logout of all portals.  Similarly, if a
.Ar portal
is specified for a remove operation, only that portal is removed from the database.  If omitted, the target including all portals are removed.
.Pp
.Pp
.Sh FILES
.Bl -tag -width Ds -compact
.It Pa /Library/Preferences/com.github.iscsi-osx.iSCSIInitiator.plist
Initiator, targets and discovery configuration file.  Stores the initiator name and alias, a list of defined targets, their associated portals, authentication parameters, session-wide and connection-wide options, discovery portals and settings and a list of discovered targets.  Superuser access is required to edit this file.
.Pp
.Sh EXAMPLES
.Bl -tag -width Ds -compact
iscsictl add target iqn.2015-01.com.example:target,192.168.1.100:3260 -interface en0
.Pp
iscsictl add target iqn.2015-01.com.example:target,192.168.1.101:3260 -interface en1
.Pp
iscsictl login iqn.2015-01.com.example:target,192.168.1.1.100
.Pp
iscsictl logout target iqn.2015-01.com.example:target
.Pp
iscsictl modify target iqn.2015-01.com.example:target,192.168.1.1.100:3260 -interface en2
.Sh SEE ALSO
.Xr iscsid 8
.Sh AUTHORS
.An Nareg Sinenian
.Aq nareg@alum.mit.edu
